version: "3.9"
services:
  screenshotbot:
    build:
      context: ${SB_OSS_CONTEXT}
      dockerfile: ${SB_OSS_DOCKERFILE}

    ports:
      - "4091:4091"
    volumes:
      - screenshotbot-oss:/data
volumes:
  screenshotbot-oss:
