version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: sudo apt-get update && sudo apt-get install -y imagemagick build-essential openjdk-11-jdk-headless sbcl libmagickwand-dev libssh2-1-dev

      - run:
          name: SBCL tests
          command: |
            for dir in /usr/lib/x86_64-linux-gnu/ImageMagick-*/bin-q* ; do
                export PATH=$PATH:$dir
            done
            echo $PATH
            which MagickWand-config
            dpkg -S MagickWand-config
            make test-sb
