version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: sudo apt-get update && sudo apt-get install -y imagemagick
