version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install Deps
          command: sudo apt-get update && sudo apt-get install -y imagemagick build-essential openjdk-11-jdk-headless
      - run:
          name: Prepare CCL
          command: curl https://github.com/Clozure/ccl/releases/download/v1.12/ccl-1.12-linuxx86.tar.gz -O ccl.tar.gz && tar xvzf ccl.tar.gz
